# Generated by Django 5.2.9 on 2026-02-12 08:03

import uuid
from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('pending', 'В ожидании'), ('processing', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='private', max_length=10, verbose_name='Статус')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('servings', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество порций')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Изображение')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('soup', 'Суп'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание'), ('side_dish', 'Гарнир')], max_length=50, verbose_name='Тип блюда')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Количество')),
                ('unit', models.CharField(blank=True, choices=[('gr', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('pc', 'шт'), ('tsp', 'ч.л.'), ('tbsp', 'ст.л.'), ('cup', 'стакан'), ('to_taste', 'по вкусу')], max_length=50, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('youtube', 'Youtube'), ('website', 'Website'), ('unknown', 'Unknown')], max_length=255, verbose_name='Источник')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('pending', 'В ожидании'), ('processing', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('metadata', models.JSONField(default=dict)),
                ('parsed_recipe', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Источник рецепта',
                'verbose_name_plural': 'Источники рецептов',
            },
        ),
    ]
