# Generated by Django 5.2.6 on 2025-09-30 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный')], default='private', max_length=10, verbose_name='Статус')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('servings', models.PositiveIntegerField(verbose_name='Количество порций')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Изображение')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание')], max_length=50, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('unit', models.CharField(choices=[('gr', 'г'), ('kg', 'кг'), ('ml', 'мл'), ('l', 'л'), ('pc', 'шт'), ('tsp', 'ч.л.'), ('tbsp', 'ст.л.'), ('cup', 'стакан'), ('to_taste', 'по вкусу')], max_length=50, verbose_name='Единица измерения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
