# Generated by Django 5.2.9 on 2026-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
