# Generated by Django 5.2.11 on 2026-03-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipesource_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4, verbose_name='Количество порций'),
        ),
    ]
