# Generated by Django 5.2.12 on 2026-03-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('soup', 'Суп'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание'), ('side_dish', 'Гарнир'), ('uncategorized', 'Без категории')], default='uncategorized', max_length=50, verbose_name='Тип блюда'),
        ),
    ]
