# Generated by Django 5.2.12 on 2026-03-19 06:40

from django.db import migrations


def set_uncategorized(apps, schema_editor):
    Recipe = apps.get_model('recipe', 'Recipe')
    Recipe.objects.filter(meal_type__in=['', None]).update(meal_type='uncategorized')


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_add_uncategorized_meal_type'),
    ]

    operations = [
        migrations.RunPython(set_uncategorized, migrations.RunPython.noop),
    ]
