# Generated by Django 5.2.6 on 2025-11-27 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipeingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('pending', 'В ожидании'), ('processing', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('metadata', models.JSONField(default=dict)),
                ('parsed_recipe', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Источник рецепта',
                'verbose_name_plural': 'Источники рецептов',
            },
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('public', 'Публичный'), ('private', 'Приватный'), ('pending', 'В ожидании'), ('processing', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='private', max_length=10, verbose_name='Статус'),
        ),
    ]
