# Generated by Django 5.2.6 on 2025-11-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipesource_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeSource',
        ),
    ]
