# Generated by Django 5.2.6 on 2025-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesource',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
