# Generated by Django 5.2.9 on 2026-01-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipesource_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
