# Generated by Django 5.2.9 on 2026-02-11 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_recipe_tips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesource',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_recipe_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipesource',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('youtube', 'Youtube'), ('website', 'Website'), ('unknown', 'Unknown')], default='instagram', max_length=50, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('soup', 'Суп'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание'), ('side_dish', 'Гарнир')], max_length=50, verbose_name='Тип блюда'),
        ),
    ]
