# Generated by Django 5.2.9 on 2026-02-11 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_recipesource_added_by_recipesource_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AddConstraint(
            model_name='recipesource',
            constraint=models.UniqueConstraint(fields=('url', 'added_by'), name='unique_recipe_per_user'),
        ),
    ]
