# Generated by Django 5.2.9 on 2026-02-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_recipesource_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipesource',
            name='unique_recipe_per_user',
        ),
        migrations.RemoveField(
            model_name='recipesource',
            name='added_by',
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipe.recipesource'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipesource',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка'),
        ),
    ]
