# Generated by Django 5.2.9 on 2026-02-12 08:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('meat', 'Мясо и птица'), ('fish', 'Рыба и морепродукты'), ('vegetables', 'Овощи'), ('fruits', 'Фрукты и ягоды'), ('dairy', 'Молочные продукты и яйца'), ('grocery', 'Крупы и бакалея'), ('oils', 'Масла и соусы'), ('bakery', 'Хлебобулочные изделия'), ('beverages', 'Напитки'), ('frozen', 'Замороженные продукты'), ('spices', 'Приправы и специи'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
