# Generated by Django 5.2.6 on 2025-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meat', 'Мясо и птица'), ('fish', 'Рыба и морепродукты'), ('vegetables', 'Овощи'), ('fruits', 'Фрукты и ягоды'), ('dairy', 'Молочные продукты и яйца'), ('grocery', 'Бакалея'), ('oils', 'Масла и соусы'), ('bakery', 'Хлебобулочные изделия'), ('beverages', 'Напитки'), ('frozen', 'Замороженные продукты'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
