# Generated by Django 5.2.6 on 2025-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('meat', 'Мясо и птица'), ('fish', 'Рыба и морепродукты'), ('vegetables', 'Овощи'), ('fruits', 'Фрукты и ягоды'), ('dairy', 'Молочные продукты и яйца'), ('grocery', 'Крупы и бакалея'), ('oils', 'Масла и соусы'), ('bakery', 'Хлебобулочные изделия'), ('beverages', 'Напитки'), ('frozen', 'Замороженные продукты'), ('spices', 'Приправы и специи'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Категория'),
        ),
    ]
