# Generated by Django 5.2.12 on 2026-03-16 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0004_alter_recipe_servings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlan',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('servings', models.PositiveIntegerField(default=2, verbose_name='Количество порций')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План меню',
                'verbose_name_plural': 'Планы меню',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MenuPlanEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('soup', 'Суп'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание'), ('side_dish', 'Гарнир')], max_length=20, verbose_name='Прием пищи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('servings', models.PositiveIntegerField(verbose_name='Количество порций')),
                ('menu_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='menu.menuplan', verbose_name='План меню')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_entries', to='recipe.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Запись в меню',
                'verbose_name_plural': 'Записи в меню',
                'ordering': ['date', 'meal_type'],
                'constraints': [models.UniqueConstraint(fields=('menu_plan', 'date', 'meal_type'), name='unique_meal_per_date')],
            },
        ),
    ]
