# Generated by Django 5.2.12 on 2026-03-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('recipe', '0004_alter_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuplanentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_entries', to='recipe.recipe', verbose_name='Рецепт'),
        ),
    ]
