# Generated by Django 5.2.12 on 2026-03-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_allow_null_recipe_in_entry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuplanentry',
            name='unique_meal_per_date',
        ),
    ]
