# Generated by Django 5.2.12 on 2026-03-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_unique_meal_per_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuplanentry',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('soup', 'Суп'), ('snack', 'Перекус'), ('dessert', 'Десерт'), ('drink', 'Напиток'), ('baby_food', 'Детское питание'), ('side_dish', 'Гарнир'), ('uncategorized', 'Без категории')], max_length=20, verbose_name='Прием пищи'),
        ),
    ]
